SELECT NAME AS WAREHOUSE_NAME, SUM(UNITS*P.VOLUME) AS volume      FROM
WAREHOUSE  W
LEFT JOIN 
(
SELECT PRODUCT_ID, WIDTH*LENGTH*HEIGHT AS VOLUME FROM PRODUCTS) P
ON P.PRODUCT_ID=W.PRODUCT_ID
GROUP BY WAREHOUSE_NAME
